name: CI
on:
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y shellcheck
      - run: find scripts -name '*.sh' -print0 | xargs -0 shellcheck
